# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test
  #query_special_suffix: '?'

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test

curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test

medical_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /data/lihuan/DPR/DPR-main/downloads/data/retriever/qas/retriver_test.csv

medical_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /data/lihuan/DPR/DPR-main/downloads/ctxdataset_retriever/candidate_val.csv

medical_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /data/lihuan/DPR/DPR-main/downloads/data/retriever/qas/retriver_train.csv